In [46]:
import pandas as pd
!pip install jupyter-dash

import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jupyter-dash in c:\users\admin\appdata\roaming\python\python39\site-packages (0.4.2)
Requirement already satisfied: nest-asyncio in c:\anaconda\lib\site-packages (from jupyter-dash) (1.5.5)
Requirement already satisfied: ipython in c:\anaconda\lib\site-packages (from jupyter-dash) (8.2.0)
Requirement already satisfied: retrying in c:\users\admin\appdata\roaming\python\python39\site-packages (from jupyter-dash) (1.3.3)
Requirement already satisfied: ipykernel in c:\anaconda\lib\site-packages (from jupyter-dash) (6.9.1)
Requirement already satisfied: dash in c:\users\admin\appdata\roaming\python\python39\site-packages (from jupyter-dash) (2.7.0)
Requirement already satisfied: ansi2html in c:\users\admin\appdata\roaming\python\python39\site-packages (from jupyter-dash) (1.8.0)
Requirement already satisfied: flask in c:\anaconda\lib\site-packages (from jupyter-dash) (1.1.2)
Requirement already satisfied: requests in c:\anaconda\lib\site-packages (from jupyter-dash) (2.27.1)
Requirement already satisfied: plotly>=5.0.0 in c:\anaconda\lib\site-packages (from dash->jupyter-dash) (5.6.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from dash->jupyter-dash) (5.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from dash->jupyter-dash) (2.0.0)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\admin\appdata\roaming\python\python39\site-packages (from dash->jupyter-dash) (2.0.0)
Requirement already satisfied: Werkzeug>=0.15 in c:\anaconda\lib\site-packages (from flask->jupyter-dash) (2.0.3)
Requirement already satisfied: click>=5.1 in c:\anaconda\lib\site-packages (from flask->jupyter-dash) (8.0.4)
Requirement already satisfied: Jinja2>=2.10.1 in c:\anaconda\lib\site-packages (from flask->jupyter-dash) (2.11.3)
Requirement already satisfied: itsdangerous>=0.24 in c:\anaconda\lib\site-packages (from flask->jupyter-dash) (2.0.1)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from click>=5.1->flask->jupyter-dash) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.23 in c:\anaconda\lib\site-packages (from Jinja2>=2.10.1->flask->jupyter-dash) (2.0.1)
Requirement already satisfied: six in c:\anaconda\lib\site-packages (from plotly>=5.0.0->dash->jupyter-dash) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\anaconda\lib\site-packages (from plotly>=5.0.0->dash->jupyter-dash) (8.0.1)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\anaconda\lib\site-packages (from ipykernel->jupyter-dash) (1.5.1)
Requirement already satisfied: traitlets<6.0,>=5.1.0 in c:\anaconda\lib\site-packages (from ipykernel->jupyter-dash) (5.1.1)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\anaconda\lib\site-packages (from ipykernel->jupyter-dash) (6.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in c:\anaconda\lib\site-packages (from ipykernel->jupyter-dash) (0.1.2)
Requirement already satisfied: jupyter-client<8.0 in c:\anaconda\lib\site-packages (from ipykernel->jupyter-dash) (6.1.12)
Requirement already satisfied: setuptools>=18.5 in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (61.2.0)
Requirement already satisfied: stack-data in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: pickleshare in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (0.7.5)
Requirement already satisfied: decorator in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (3.0.20)
Requirement already satisfied: jedi>=0.16 in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (0.18.1)
Requirement already satisfied: backcall in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: pygments>=2.4.0 in c:\anaconda\lib\site-packages (from ipython->jupyter-dash) (2.11.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\anaconda\lib\site-packages (from jedi>=0.16->ipython->jupyter-dash) (0.8.3)
Requirement already satisfied: pyzmq>=13 in c:\anaconda\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter-dash) (22.3.0)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\anaconda\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter-dash) (4.9.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda\lib\site-packages (from jupyter-client<8.0->ipykernel->jupyter-dash) (2.8.2)
Requirement already satisfied: pywin32>=1.0 in c:\anaconda\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client<8.0->ipykernel->jupyter-dash) (302)
Requirement already satisfied: wcwidth in c:\anaconda\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-dash) (0.2.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda\lib\site-packages (from requests->jupyter-dash) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\anaconda\lib\site-packages (from requests->jupyter-dash) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests->jupyter-dash) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda\lib\site-packages (from requests->jupyter-dash) (3.3)
Requirement already satisfied: pure-eval in c:\anaconda\lib\site-packages (from stack-data->ipython->jupyter-dash) (0.2.2)
Requirement already satisfied: asttokens in c:\anaconda\lib\site-packages (from stack-data->ipython->jupyter-dash) (2.0.5)
Requirement already satisfied: executing in c:\anaconda\lib\site-packages (from stack-data->ipython->jupyter-dash) (0.8.3)

In [32]:
ntrs = pd.read_csv(r"C:\Users\Admin\Downloads\NTRS_Dataset.csv")
ntrs.head()

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,3-Jan-12,NaN,0.971440,0.376,NaN,NaN,1.8485,1.2925,1.0090,518.20,...,NaN,0.9334,NaN,NaN,1.4987,3.6725,0.640574,1,19.700,NaN
1,4-Jan-12,NaN,0.965904,0.376,4.2893,7.490637,1.8304,1.2874,1.0135,514.34,...,6.8152,0.9384,31.463,6.4062,1.4942,3.6725,0.641190,1,19.689,NaN
2,5-Jan-12,NaN,0.968711,0.376,4.2893,7.530120,1.8432,1.2883,1.0197,512.23,...,6.8493,0.9492,31.557,6.3886,1.4951,3.6725,0.644330,1,19.707,NaN
3,6-Jan-12,76.3243,0.978378,0.376,4.2893,7.530120,1.8416,1.2923,1.0232,511.80,...,NaN,0.9516,31.637,6.3994,1.5046,3.6725,0.645245,1,NaN,NaN
4,9-Jan-12,76.5183,0.983284,0.376,4.2893,7.530120,1.8442,1.2994,1.0272,509.54,...,6.9227,0.9520,31.793,6.3931,1.5145,3.6725,0.647585,1,19.650,NaN

In [33]:
ntrs.isnull()

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,False,True,False,False,True,True,False,False,False,False,...,True,False,True,True,False,False,False,False,False,True
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2644,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2645,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2646,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,True
2647,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,True,True,False,False,False,True

In [34]:
ntrs['Date'] = pd.to_datetime(ntrs['Date']).dt.date

In [35]:
ntrs

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,2012-01-03,NaN,0.971440,0.376,NaN,NaN,1.8485,1.2925,1.0090,518.20,...,NaN,0.9334,NaN,NaN,1.4987,3.6725,0.640574,1,19.700,NaN
1,2012-01-04,NaN,0.965904,0.376,4.2893,7.490637,1.8304,1.2874,1.0135,514.34,...,6.8152,0.9384,31.463,6.4062,1.4942,3.6725,0.641190,1,19.689,NaN
2,2012-01-05,NaN,0.968711,0.376,4.2893,7.530120,1.8432,1.2883,1.0197,512.23,...,6.8493,0.9492,31.557,6.3886,1.4951,3.6725,0.644330,1,19.707,NaN
3,2012-01-06,76.3243,0.978378,0.376,4.2893,7.530120,1.8416,1.2923,1.0232,511.80,...,NaN,0.9516,31.637,6.3994,1.5046,3.6725,0.645245,1,NaN,NaN
4,2012-01-09,76.5183,0.983284,0.376,4.2893,7.530120,1.8442,1.2994,1.0272,509.54,...,6.9227,0.9520,31.793,6.3931,1.5145,3.6725,0.647585,1,19.650,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,2022-08-22,141.0594,1.450958,NaN,NaN,12.787724,5.1703,1.3927,1.3035,945.35,...,10.6251,0.9587,35.938,6.7687,NaN,3.6725,0.847170,1,40.431,NaN
2644,2022-08-23,141.2180,1.454122,NaN,NaN,12.836970,5.1024,1.3971,1.2972,945.47,...,10.7180,0.9667,36.226,6.7560,NaN,3.6725,0.850051,1,40.369,NaN
2645,2022-08-24,140.9474,1.448226,NaN,NaN,12.836970,5.1044,1.3955,1.2983,926.94,...,10.6617,0.9640,36.162,6.7701,NaN,3.6725,0.849185,1,40.401,NaN
2646,2022-08-25,140.6518,1.437815,NaN,NaN,12.738853,5.1167,1.3916,1.2937,915.60,...,10.5645,0.9638,35.894,6.7554,NaN,3.6725,0.845594,1,NaN,NaN
2647,2022-08-26,140.4196,1.437401,NaN,NaN,12.738853,5.0897,1.3904,1.2989,910.03,...,10.6006,0.9628,35.900,6.7171,NaN,NaN,0.844951,1,40.421,NaN

In [36]:
ntrs.interpolate(inplace = True)
ntrs

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,2012-01-03,NaN,0.971440,0.376,NaN,NaN,1.8485,1.2925,1.0090,518.20,...,NaN,0.9334,NaN,NaN,1.49870,3.6725,0.640574,1,19.7000,NaN
1,2012-01-04,NaN,0.965904,0.376,4.2893,7.490637,1.8304,1.2874,1.0135,514.34,...,6.8152,0.9384,31.463,6.4062,1.49420,3.6725,0.641190,1,19.6890,NaN
2,2012-01-05,NaN,0.968711,0.376,4.2893,7.530120,1.8432,1.2883,1.0197,512.23,...,6.8493,0.9492,31.557,6.3886,1.49510,3.6725,0.644330,1,19.7070,NaN
3,2012-01-06,76.3243,0.978378,0.376,4.2893,7.530120,1.8416,1.2923,1.0232,511.80,...,6.8860,0.9516,31.637,6.3994,1.50460,3.6725,0.645245,1,19.6785,NaN
4,2012-01-09,76.5183,0.983284,0.376,4.2893,7.530120,1.8442,1.2994,1.0272,509.54,...,6.9227,0.9520,31.793,6.3931,1.51450,3.6725,0.647585,1,19.6500,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,2022-08-22,141.0594,1.450958,0.376,248209.9200,12.787724,5.1703,1.3927,1.3035,945.35,...,10.6251,0.9587,35.938,6.7687,2.99612,3.6725,0.847170,1,40.4310,562.57005
2644,2022-08-23,141.2180,1.454122,0.376,248209.9200,12.836970,5.1024,1.3971,1.2972,945.47,...,10.7180,0.9667,36.226,6.7560,2.99612,3.6725,0.850051,1,40.3690,562.57005
2645,2022-08-24,140.9474,1.448226,0.376,248209.9200,12.836970,5.1044,1.3955,1.2983,926.94,...,10.6617,0.9640,36.162,6.7701,2.99612,3.6725,0.849185,1,40.4010,562.57005
2646,2022-08-25,140.6518,1.437815,0.376,248209.9200,12.738853,5.1167,1.3916,1.2937,915.60,...,10.5645,0.9638,35.894,6.7554,2.99612,3.6725,0.845594,1,40.4110,562.57005
2647,2022-08-26,140.4196,1.437401,0.376,248209.9200,12.738853,5.0897,1.3904,1.2989,910.03,...,10.6006,0.9628,35.900,6.7171,2.99612,3.6725,0.844951,1,40.4210,562.57005

In [37]:
ntrs.fillna(method = 'bfill', inplace = True)
ntrs

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,2012-01-03,76.3243,0.971440,0.376,4.2893,7.490637,1.8485,1.2925,1.0090,518.20,...,6.8152,0.9334,31.463,6.4062,1.49870,3.6725,0.640574,1,19.7000,3690.94950
1,2012-01-04,76.3243,0.965904,0.376,4.2893,7.490637,1.8304,1.2874,1.0135,514.34,...,6.8152,0.9384,31.463,6.4062,1.49420,3.6725,0.641190,1,19.6890,3690.94950
2,2012-01-05,76.3243,0.968711,0.376,4.2893,7.530120,1.8432,1.2883,1.0197,512.23,...,6.8493,0.9492,31.557,6.3886,1.49510,3.6725,0.644330,1,19.7070,3690.94950
3,2012-01-06,76.3243,0.978378,0.376,4.2893,7.530120,1.8416,1.2923,1.0232,511.80,...,6.8860,0.9516,31.637,6.3994,1.50460,3.6725,0.645245,1,19.6785,3690.94950
4,2012-01-09,76.5183,0.983284,0.376,4.2893,7.530120,1.8442,1.2994,1.0272,509.54,...,6.9227,0.9520,31.793,6.3931,1.51450,3.6725,0.647585,1,19.6500,3690.94950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,2022-08-22,141.0594,1.450958,0.376,248209.9200,12.787724,5.1703,1.3927,1.3035,945.35,...,10.6251,0.9587,35.938,6.7687,2.99612,3.6725,0.847170,1,40.4310,562.57005
2644,2022-08-23,141.2180,1.454122,0.376,248209.9200,12.836970,5.1024,1.3971,1.2972,945.47,...,10.7180,0.9667,36.226,6.7560,2.99612,3.6725,0.850051,1,40.3690,562.57005
2645,2022-08-24,140.9474,1.448226,0.376,248209.9200,12.836970,5.1044,1.3955,1.2983,926.94,...,10.6617,0.9640,36.162,6.7701,2.99612,3.6725,0.849185,1,40.4010,562.57005
2646,2022-08-25,140.6518,1.437815,0.376,248209.9200,12.738853,5.1167,1.3916,1.2937,915.60,...,10.5645,0.9638,35.894,6.7554,2.99612,3.6725,0.845594,1,40.4110,562.57005
2647,2022-08-26,140.4196,1.437401,0.376,248209.9200,12.738853,5.0897,1.3904,1.2989,910.03,...,10.6006,0.9628,35.900,6.7171,2.99612,3.6725,0.844951,1,40.4210,562.57005

In [38]:
ntrs.isnull()

,Date,Algerian dinar (DZD),Australian dollar (AUD),Bahrain dinar (BHD),Bolivar Fuerte (VEF),Botswana pula (BWP),Brazilian real (BRL),Brunei dollar (BND),Canadian dollar (CAD),Chilean peso (CLP),...,Swedish krona (SEK),Swiss franc (CHF),Thai baht (THB),Trinidadian dollar (TTD),Tunisian dinar (TND),U.A.E. dirham (AED),U.K. pound (GBP),U.S. dollar (USD),Uruguayan peso (UYU),Bolivar Soberano (VES)
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2644,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2645,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2646,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2647,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [39]:
ntrs.to_csv('NTRS.csv')